config/routes.rb
Rails.application.routes.draw do
  resources :restos do

  collection do
    get 'random', to: 'restos#random', as: 'random' 
    get 'popular', to: 'restos#most_popular', as: 'popular' 
    get 'starred', to: 'restos#starred_restos', as: 'starred'
  end
end

  devise_for :users

  post 'star', to: 'stars#star', via: :resto

  match 'unstar', to: 'stars#unstar', via: :delete

  root 'restos#index'

end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :resto

  belongs_to :user

  validates :user_id, uniqueness: { scope: :resto_id }

  
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  respond_to :js

def star
  @user = current_user
  @resto = Resto.find(params[:resto_id])
  @user.star!(@resto)
  @star_count = @resto.stars.count
end

def unstar
  @user = current_user
  @star = @user.stars.find_by_resto_id(params[:resto_id])
  @resto = Resto.find(params[:resto_id])
  @star.destroy!
  @star_count = @resto.stars.count
end

end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/stars/_button.html.erb
<% if !user_signed_in? %>
  <i class='fas fa-star'></i>
  <%= @star_count %>
<% else %>
<% if current_user.star?(resto) %>
  <%= link_to unstar_path(resto_id: resto.id), remote: true, method: :delete do %>
  <i class='fas fa-star'></i>
  <%= @star_count %>
  <% end %>
<% else %>
  <%= link_to star_path(resto_id: resto.id), remote: true, method: :post do %>
  <i class='far fa-star'></i>
  <%= @star_count %>
  <% end %>
<% end %>
<% end %>

app/views/stars/star.js.erb
$('div#<%= dom_id(@resto) %>').html('<%= j render partial: "button", locals: {resto: @resto} %>');

app/views/stars/unstar.js.erb
$('div#<%= dom_id(@resto) %>').html('<%= j render partial: "button", locals: {resto: @resto} %>');