config/routes.rb
Rails.application.routes.draw do
  resources :restos do

  collection do
    get 'random', to: 'restos#random', as: 'random' 
    get 'popular', to: 'restos#most_popular', as: 'popular' 
    get 'starred', to: 'restos#starred_restos', as: 'starred'
  end
end

  devise_for :users

  post 'star', to: 'stars#star', via: :resto

  match 'unstar', to: 'stars#unstar', via: :delete

  root 'restos#index'

end

app/models/resto.rb
class Resto < ActiveRecord::Base
  resourcify
  paginates_per 5
  has_many :stars, dependent: :destroy
  has_many :users, through: :stars
  belongs_to :cuisine

  validates :name, presence: true
  validates :address, presence: true
  validates :contact, presence: true
  validates :cuisine_id, presence: true
  
end

app/controllers/restos_controller.rb
class RestosController < ApplicationController
  before_action :set_resto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :random, :most_popular]
  authorize_resource class: false, except: [:index, :show, :random, :most_popular] 
  # GET /restos
  # GET /restos.json
  def index  
    if params[:cuisine]. blank?
    @restos = Resto.includes(:stars).order(created_at: :desc).page params[:page]
    else
      @cuisine_id = Cuisine.find_by(name: params[:cuisine]).id
      @restos = Resto.where(cuisine_id: @cuisine_id).order("created_at DESC").page params[:page]
    end
  end

  # GET /restos/1
  # GET /restos/1.json
  def show
    @resto = Resto.find_by_id(params[:id])
    @star_count = @resto.stars.count
  end

  # GET /restos/new
  def new
    @resto = Resto.new
  end

  # GET /restos/1/edit
  def edit
  end

  # POST /restos
  # POST /restos.json
  def create
    @resto = Resto.new(resto_params)

    respond_to do |format|
      if @resto.save
        format.html { redirect_to @resto, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @resto }
      else
        format.html { render :new }
        format.json { render json: @resto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restos/1
  # PATCH/PUT /restos/1.json
  def update
    respond_to do |format|
      if @resto.update(resto_params)
        format.html { redirect_to @resto, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @resto }
      else
        format.html { render :edit }
        format.json { render json: @resto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restos/1
  # DELETE /restos/1.json
  def destroy
    @resto.destroy
    respond_to do |format|
      format.html { redirect_to restos_url, notice: 'Entry was deleted.' }
      format.json { head :no_content }
    end
  end

  def most_popular
    @restos = Resto.joins('LEFT JOIN (select resto_id, count(*) as star_count from stars group by resto_id) as stars on restos.id = stars.resto_id').order('star_count desc').page params[:page]
    render 'index'
  end

  def starred_restos
    @user = current_user.id
    @restos = Resto.joins(:users).where("user_id = " +  @user.to_s ).page params[:page]
    render 'index'
  end

    def random
     @restos = Resto.order("RANDOM()").take(3)
     render 'index'
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resto
      @resto = Resto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resto_params
      params.require(:resto).permit(:name, :address, :contact, :cuisine_id)
    end
    
end

app/helpers/restos_helper.rb
module RestosHelper
end

app/views/restos/_form.html.haml
= simple_form_for @resto, html: { multipart: true } do |f|
    - if @resto.errors.any?
        #errors
            %p
                = @resto.errors.count
                Prevented this resto froms saving
            %ul
                - @resto.errors.full_messages.each do |msg|
                    %li= msg
    .panel-body
    = f.input :name, input_html: { class: 'form-control' }
    = f.input :address, input_html: { class: 'form-control' }
    = f.input :contact, input_html: { class: 'form-control' }
    = f.collection_select :cuisine_id, Cuisine.all, :id, :name, {prompt: "Choose a cuisine", class: 'form-control' }
    = f.button :submit, class: "btn btn-primary"

app/views/restos/edit.html.haml
%h1 Edit Restaurant 

= render 'form'

app/views/restos/index.html.erb
<div class ="container">
<div class="row">
   <div class= "col-md-12">
   <div class="row">
   <div class= "col-md-4">
   <div class="panel panel-default">
  <div class="panel-heading">Sort By</div>
  <div class="panel-body">
  <ul>
  <li><%= link_to "Starred Restaurants", starred_restos_path %></li>
  <li><%= link_to "Most Popular Restaurants", popular_restos_path %></li>
  </ul>
  </div>
</div>
   </div>
   <div class= "col-md-8">
     <% @restos.each do |resto| %>
      <div id="resto_info">     
        <h1>
          <%= link_to resto.name, resto, style: 'color:#FFFFF;' %>
        </h1>
        <p class="description">
          <%= resto.address %>
        </p>
        <p class="description">
          <%= resto.cuisine.name %>
          <p class="description">
          <%= resto.contact %>
          </p>
          <%= div_for resto do %>
					<%= render partial: "stars/button", locals: { resto: resto } %>
          <%= resto.stars.count %>
          <% end %>
        </p> 
  </div>
    <% end %>     
  <% if current_page?(action: 'random') %>
  <% else %>
  <%= paginate @restos %>
  <% end %>
  </div>
  </div>

  </div>
  </div>
  </div>

app/views/restos/new.html.haml
%h1 New Restaurant
=render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/restos/show.html.haml
.main_content
	#resto_top.row
		.col-md-8
			#resto_info
				%h1= @resto.name
				%p.description= @resto.address
				%p.description= @resto.cuisine.name
				%p.description= @resto.contact
				= div_for @resto do
					= render partial: "stars/button", locals: { resto: @resto }
				- if current_user && current_user.has_role?(:admin)
					= link_to "Back", root_path, class: "btn btn-default"
					= link_to "Edit", edit_resto_path, class: "btn btn-default",  data: { no_turbolink: true }
					= link_to "Delete", resto_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"
				