config/routes.rb
Rails.application.routes.draw do
  resources :restos do

  collection do
    get 'random', to: 'restos#random', as: 'random' 
    get 'popular', to: 'restos#most_popular', as: 'popular' 
    get 'starred', to: 'restos#starred_restos', as: 'starred'
  end
end

  devise_for :users

  post 'star', to: 'stars#star', via: :resto

  match 'unstar', to: 'stars#unstar', via: :delete

  root 'restos#index'

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
    %title Tomato
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    = javascript_include_tag 'application', 'https://kit.fontawesome.com/8b7a173684.js'
    = csrf_meta_tags

%body
    %nav.navbar.navbar-default
        .container
            .navbar-brand= link_to "Tomato", root_path
            %ul.nav.navbar-nav
                %li= link_to "All Cuisines", root_path
                %li= link_to "Random", random_restos_path
                - Cuisine.all.each do |cuisine| # listing categories
                    %li= link_to cuisine.name, restos_path(cuisine: cuisine.name)
            - if user_signed_in? && current_user && current_user.has_role?(:admin)
                %ul.nav.navbar-nav.navbar-right
                    %li= link_to "New Restaurant", new_resto_path,  data: { no_turbolink: true }
                    %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - elsif user_signed_in? && current_user
                %ul.nav.navbar-nav.navbar-right
                    %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
                %ul.nav.navbar-nav.navbar-right
                    %li= link_to "Sign Up", new_user_registration_path
                    %li= link_to "Sign In", new_user_session_path

    .container
        - flash.each do |name, msg|
            = content_tag :div, msg, class: "alert"

        = yield